# Generated by Django 6.0.7 on 2026-08-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=64, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
            ],
        ),
    ]
