# Generated by Django 6.0.7 on 2026-08-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='colour_preference',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('orange', 'Orange'), ('pink', 'Pink'), ('white', 'White')], default='red', max_length=20),
        ),
    ]
