# Generated by Django 6.0.7 on 2026-08-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_userprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='colour_preference',
            field=models.CharField(default='red', max_length=50),
        ),
    ]
